---
concurrency: 5
queues:
  - scheduler
  - polling
  - default

:schedule:
  sync_source_enqueuer:
    every: ["15s"]
    class: "SyncSourceEnqueuerWorker"
    queue: scheduler

production:
  concurrency: 10

staging:
  concurrency: 5

development:
  concurrency: 5

